---
title: "Study tables, MetaPhlAn alpha and beta diversities"
author: "Giacomo Antonello"
date: "`r Sys.Date()`"
format: 
  html:
    embed-resources: true
    toc: true
    toc-depth: 2
editor: source
params:
  biobakery_tool: "MetaPhlAn"
  BugSigDB_version: 1.3.1
---

```{r setup}
library(kableExtra)
library(magrittr)
library(tidyverse)
library(bugsigdbr)
library(bugSigSimple) # BiocManager::install("waldronlab/bugSigSimple", dependencies = TRUE)

outdir <- file.path("results", "00-BugSigDB")
dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

bsdb_zenodo_entry <- "https://doi.org/10.5281/zenodo.19740674"
 
bsdb_versions <- suppressMessages(zen4R::get_versions(bsdb_zenodo_entry))
bsdb_versioned_doi <- bsdb_versions$doi[bsdb_versions$version == paste0("v", params$BugSigDB_version)]

bugsigdb.df <- importBugSigDB(version = bsdb_versioned_doi, cache = FALSE)
```

```{r, echo=TRUE}
# define query
query.list <- list(
  Condition = "Parkinson's disease", 
  "Body site" = "Feces",
  "EFO ID" = "MONDO:0005180",
  "Host species" = "Homo sapiens",
  "Study design" = "case-control"
  )

unlist(query.list) %>% 
  as.data.frame() %>% 
  kbl() %>% 
  kable_styling()
```

```{r}
bugsigdb_human_feces.df <- bugsigdb.df %>% 
  filter(`Body site` == query.list$`Body site`, `Host species` == query.list$`Host species`, `Study design` == query.list$`Study design`)
```

## Most studied conditions in bugsigdb

```{r}
studies_by_condition_in_gut <- bugsigdb_human_feces.df %>%
  group_by(Condition) %>%
  reframe(
    nStudies = length(unique(Study)),
    nSignatures = n(),
    `Signature/Study ratio` = round(nSignatures/nStudies, 2),
    `Signature Mean length (SD)` = sprintf("%.1f (%.1f)", mean(lengths(
      `MetaPhlAn taxon names`
    )), sd(lengths(
      `MetaPhlAn taxon names`
    )))
  ) %>%
  arrange(desc(nStudies))
```

```{r}
write_tsv(studies_by_condition_in_gut, file = file.path(outdir, "01-studies_and_signatures_per_condition.tsv"))
DT::datatable(studies_by_condition_in_gut)
```

## PD taxa table

```{r}
bugsigdb_human_feces_PD.df <- filter(bugsigdb_human_feces.df, Condition == query.list$Condition) 
```

```{r}
tmp_UP <- bugsigdb_human_feces_PD.df %>% 
  getSignatures(tax.id.type = "metaphlan", tax.level = "genus") %>% 
  .[grepl("_UP", names(.))]

tmp_DOWN <- bugsigdb_human_feces_PD.df %>% 
  getSignatures(tax.id.type = "metaphlan", tax.level = "genus") %>% 
  .[grepl("_DOWN", names(.))]

signatures_down_genus <- lapply(tmp_DOWN, as.data.frame) %>% 
  bind_rows(.id = "signature_id") %>% 
  set_names(c("signature_id", "taxonomy")) %>% group_by(taxonomy) %>% 
  reframe(n_signatures_present = n()) %>% 
  separate_wider_delim(cols = taxonomy, delim = "|", names = c("kingdom", "phylum", "class", "order", "family", "genus"), too_few = "align_start")

signatures_up_genus <- lapply(tmp_UP, as.data.frame) %>% 
  bind_rows(.id = "signature_id") %>% 
  set_names(c("signature_id", "taxonomy")) %>% group_by(taxonomy) %>% 
  reframe(n_signatures_present = n()) %>% 
  separate_wider_delim(cols = taxonomy, delim = "|", names = c("kingdom", "phylum", "class", "order", "family", "genus"), too_few = "align_start", too_many = "debug")
```


```{r}
PD_taxa_table <- createTaxonTable(bugsigdb_human_feces_PD.df, n = 100) %>% 
  set_names(c("Taxon Name",	"Taxonomic Level", "N. signatures",	"Increased",	"Decreased",	"Binomial Test P-value"))

# write full table
write_tsv(PD_taxa_table, file = file.path(outdir, "02-taxa_table_in_PD.tsv"))

# write series of tables split by 
DT::datatable(PD_taxa_table)
```

# Session Info

```{r}
sessionInfo()
```
