---
title: "Forest plots"
author: "Giacomo Antonello"
date: "`r Sys.Date()`"
format: 
  html:
    embed-resources: true
    toc: true
    toc-depth: 2
editor: source
params:
 overwrite_TSE_out: "yes"
---

```{r}
library(tidyverse)
library(openxlsx2)
library(knitr)
library(ggpubr)
theme_set(theme_bw())
set.seed(1234)
#------------------------------
# some parameters
P_adj_thr <- 0.2
topN_feat <- 20
#---------------------------
source("../utils/mbForestPlot.R")

MetaPhlAn_maslin2_results_path <- sprintf("../02-Analyses/results/02-PD-meta-analysis/MetaPhlAn/02-MetaPhlAn_MetaAnalysis_results_maaslin2.xlsx")
res <- read_xlsx(MetaPhlAn_maslin2_results_path, sheet = "MetaAnalysis")

tmp_wb <- wb_load(MetaPhlAn_maslin2_results_path)
MetaPhlAn_results.list <- sapply(tmp_wb$sheet_names, function(sheet) wb_to_df(tmp_wb, sheet), simplify = FALSE)

# Change function behavior: 
# - from path to results list
# - make sure topN function works
# - allow decreasing and increasing order
forest_plot_MetaPhlAn <- ForestPlot_biobakery(MetaPhlAn_results.list,P_adj_thr = P_adj_thr, topN_feat = topN_feat)

kable(forest_plot_MetaPhlAn$label_ranks) %>% kableExtra::kable_styling(full_width = FALSE)
forest_plot_MetaPhlAn$plot
```

```{r}
tmp <- MetaPhlAn_results.list$MetaAnalysis %>%
  filter(P.Value.adj < P_adj_thr) %>%
  prepare_featuresCol()

meta_df                <- tmp[[1]]
featuresCol_transl_vec <- tmp[[2]]

# get top N results — now correctly uses its own `res` arg
topN_df <- get_res_topN_features(
  res       = MetaPhlAn_results.list$MetaAnalysis,
  topN_feat = topN_feat,
  P_adj_thr = P_adj_thr
)

# attach featuresCol on the topN data frame
featureID_col <- colnames(MetaPhlAn_results.list$MetaAnalysis)[grep("StudiesTested", colnames(MetaPhlAn_results.list$MetaAnalysis)) - 1]

topN_df <- topN_df %>%
  mutate(featuresCol = featuresCol_transl_vec[.data[[featureID_col]]])

# order vector of features based on the `decreasing` parameter
selected_features_ordered <- topN_df$featuresCol[order(topN_df$Beta.pool)]

topN_df$featuresCol <- factor(topN_df$featuresCol, levels = selected_features_ordered)

heterogeneity_plot_MetaPhlAn <- ggplot(topN_df, aes(x = Het.I2, y = featuresCol, fill = Het.Pval >= 0.1)) + 
  geom_col(size = 2.5, pch = 21, color = "gray40") + 
  geom_vline(xintercept = 30, lty = "dashed") + 
  labs(
    x = expression(Heterogeneity~(I^2))
  )

Forest_and_het_panel <- ggarrange(
  forest_plot_MetaPhlAn$plot,
  heterogeneity_plot_MetaPhlAn + theme(axis.text.y = element_blank(), axis.title.y = element_blank(), legend.position = "none"), 
  widths = c(1, 0.2), 
  align = "h"
)

ggsave(plot = Forest_and_het_panel, filename = file.path("results", "01-forestPlot-MetaPhlAn.svg"), height = 8, width = 10)
```

```{r}
HUMAnN_maslin2_results_path <- sprintf("../02-Analyses/results/02-PD-meta-analysis/HUMAnN/02-HUMAnN_MetaAnalysis_results_maaslin2.xlsx")
res <- read_xlsx(HUMAnN_maslin2_results_path, sheet = "MetaAnalysis")

tmp_wb <- wb_load(HUMAnN_maslin2_results_path)
HUMAnN_results.list <- sapply(tmp_wb$sheet_names, function(sheet) wb_to_df(tmp_wb, sheet), simplify = FALSE)

# Change function behavior: 
# - from path to results list
# - make sure topN function works
# - allow decreasing and increasing order
forest_plot_HUMAnN <- ForestPlot_biobakery(HUMAnN_results.list, topN_feat = 20,P_adj_thr = 0.1, decreasing = TRUE)

kable(forest_plot_HUMAnN$label_ranks) %>% kableExtra::kable_styling(full_width = FALSE)
```

```{r}
tmp <- HUMAnN_results.list$MetaAnalysis %>%
  filter(P.Value.adj < P_adj_thr) %>%
  prepare_featuresCol()

meta_df                <- tmp[[1]]
featuresCol_transl_vec <- tmp[[2]]

# get top N results — now correctly uses its own `res` arg
topN_df <- get_res_topN_features(
  res       = HUMAnN_results.list$MetaAnalysis,
  topN_feat = topN_feat,
  P_adj_thr = P_adj_thr
)

# attach featuresCol on the topN data frame
featureID_col <- colnames(HUMAnN_results.list$MetaAnalysis)[grep("StudiesTested", colnames(HUMAnN_results.list$MetaAnalysis)) - 1]

topN_df <- topN_df %>%
  mutate(featuresCol = featuresCol_transl_vec[.data[[featureID_col]]])

# order vector of features based on the `decreasing` parameter
selected_features_ordered <- topN_df$featuresCol[order(topN_df$Beta.pool)]

topN_df$featuresCol <- factor(topN_df$featuresCol, levels = selected_features_ordered)

heterogeneity_plot_HUMAnN <- ggplot(topN_df, aes(x = Het.I2, y = featuresCol, fill = Het.Pval >= 0.1)) + 
  geom_col(size = 2.5, pch = 21, color = "gray40") + 
  geom_vline(xintercept = 30, lty = "dashed") + 
  labs(
    x = expression(Heterogeneity~(I^2))
  )

Forest_and_het_panel <- ggarrange(
  forest_plot_HUMAnN$plot,
  heterogeneity_plot_HUMAnN + theme(axis.text.y = element_blank(), axis.title.y = element_blank(), legend.position = "none"), 
  widths = c(1, 0.2), 
  align = "h"
)

ggsave(plot = Forest_and_het_panel, filename = file.path("results", "02-forestPlot-HUMAnN.svg"), height = 8, width = 10)
```

QianY (8) and Bedarf (1) pathway associations are generally outliers, as they 
are rather strong and in the opposite direction as the meta

# Figure 2 panel

```{r prepare single panels}

panelA <- forest_plot_MetaPhlAn$plot + labs(caption = NULL, y = NULL)

panelB <- heterogeneity_plot_MetaPhlAn + 
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y.left = element_blank()
  ) +
  scale_x_continuous(
    breaks = seq(0, 90, by = 20),
    limits = c(0, 90),
    expand = c(0, 0)
  ) +
  labs(y = NULL)

panelC <- forest_plot_HUMAnN$plot + labs(caption = NULL, y = NULL)

panelD <- heterogeneity_plot_HUMAnN + 
    theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y.left = element_blank()
  ) +
  scale_x_continuous(
    breaks = seq(0, 90, by = 20),
    limits = c(0, 90),
    expand = c(0, 0)
  ) +
  labs(y = NULL)

study_labels_vertical <- forest_plot_HUMAnN$label_ranks %>%
  mutate(tmp = paste0(study_rank, ") ", study_label)) %>% 
  pluck("tmp") %>%  
  ggtexttable(theme = ttheme(
      colnames.style = colnames_style(fill = "white", color = "black", linewidth = 0),
      tbody.style = tbody_style(
        fill = "white", 
        color = "black", 
        linewidth = 0, 
        linecolor = "transparent", hjust = 0, x=0.1
      )))

study_labels_horizontal <- forest_plot_HUMAnN$label_ranks %>%
  mutate(tmp = paste0(study_rank, ") ", study_label)) %>% 
  pluck("tmp") %>%  
  # add empty text to obtain a vector of even length to wrap it into 2 row matrix
  c(., " ") %>% 
  matrix(nrow = 2, byrow = TRUE) %>% 
  ggtexttable(theme = ttheme(
      colnames.style = colnames_style(fill = "white", color = "black", linewidth = 0),
      tbody.style = tbody_style(
        fill = "white", 
        color = "black", 
        size = 9,
        linewidth = 0, 
        linecolor = "transparent", hjust = 0, x = 0.1
      )))

legend_row <- ggplot() + theme_void() +
  inset_element(
    study_labels_horizontal,
    left = 0.4, right = 0.85,   # symmetric margins -> horizontally centered
    bottom = -0.3, top = 0.7,     # occupies the lower 70% -> sits toward the bottom
    align_to = "full"
  )
```

```{r build panels}
library(patchwork)

panelABCD <- wrap_plots(panelA, panelB, panelC, panelD, ncol = 2) + 
  plot_layout(
    widths = c(1, 0.3),
    heights = c(1, 1)
  ) +
  plot_annotation(tag_levels = "a")   # tags a-d applied ONLY to these four panels

legend_row <- ggplot() + theme_void() +
  inset_element(
    study_labels_horizontal,
    left = 0.4, right = 0.85,
    bottom = -0.3, top = 0.5,
    align_to = "full"
  ) +
  theme(plot.tag = element_blank())   # belt-and-suspenders: no tag drawn here even if assigned

Figure1 <- wrap_plots(
  legend_row,
  wrap_elements(panelABCD),   # protects panelABCD's tags from being reset
  nrow = 2
) +
  plot_layout(heights = c(0.2, 1))

ggsave(plot = Figure1, filename = file.path("results", "Figure2-PD-meta-analysis.svg"), height = 10, width = 10)
```

# Session Info

```{r session info}
sessionInfo()
```

